-- AlterTable
ALTER TABLE `Machine` ADD COLUMN `mode` VARCHAR(20) NOT NULL DEFAULT 'cloud';
ALTER TABLE `Machine` ADD COLUMN `ip` VARCHAR(64) NULL;
ALTER TABLE `Machine` ADD COLUMN `port` INTEGER NULL;
